-- Oracle SQL Conversion

-- Note: Oracle does not have a direct equivalent of SET FOREIGN_KEY_CHECKS.
-- Constraints are managed individually or through deferrable constraints.
-- For script re-runnability, we will drop tables if they exist.

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Role CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE Role (
                      RoleID      VARCHAR2(20 CHAR) PRIMARY KEY,
                      RoleName    VARCHAR2(50 CHAR) NOT NULL UNIQUE,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Oracle uses MERGE for ON DUPLICATE KEY UPDATE
MERGE INTO Role t
USING (SELECT 'student' AS RoleID, 'Học sinh' AS RoleName FROM DUAL) s
ON (t.RoleID = s.RoleID)
WHEN NOT MATCHED THEN
    INSERT (RoleID, RoleName, created_at)
    VALUES (s.RoleID, s.RoleName, CURRENT_TIMESTAMP)
WHEN MATCHED THEN
    UPDATE SET t.RoleName = s.RoleName; -- Original did RoleName = RoleName, this updates if different

MERGE INTO Role t
USING (SELECT 'instructor' AS RoleID, 'Giảng viên' AS RoleName FROM DUAL) s
ON (t.RoleID = s.RoleID)
WHEN NOT MATCHED THEN
    INSERT (RoleID, RoleName, created_at)
    VALUES (s.RoleID, s.RoleName, CURRENT_TIMESTAMP)
WHEN MATCHED THEN
    UPDATE SET t.RoleName = s.RoleName;

MERGE INTO Role t
USING (SELECT 'admin' AS RoleID, 'Quản trị viên' AS RoleName FROM DUAL) s
ON (t.RoleID = s.RoleID)
WHEN NOT MATCHED THEN
    INSERT (RoleID, RoleName, created_at)
    VALUES (s.RoleID, s.RoleName, CURRENT_TIMESTAMP)
WHEN MATCHED THEN
    UPDATE SET t.RoleName = s.RoleName;

-- 2. Users
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Users CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE Users (
                       UserID   VARCHAR2(40 CHAR) PRIMARY KEY,
                       FirstName     VARCHAR2(100 CHAR) NOT NULL,
                       LastName VARCHAR2(100 CHAR) NOT NULL,
                       Email    VARCHAR2(100 CHAR) NOT NULL UNIQUE,
                       Password VARCHAR2(255 CHAR) NOT NULL, -- Storing passwords as hashes, CHAR or BYTE semantics depends on hash output
                       RoleID   VARCHAR2(36 CHAR) NOT NULL,
                       ProfileImage  VARCHAR2(255 CHAR),
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                       FOREIGN KEY (RoleID) REFERENCES Role(RoleID)
);

-- 3. Instructor
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Instructor CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE Instructor (
                            InstructorID  VARCHAR2(40 CHAR) PRIMARY KEY,
                            UserID        VARCHAR2(40 CHAR) NOT NULL UNIQUE,
                            Biography     CLOB,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

-- 4. Student
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Student CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE Student (
                         StudentID       VARCHAR2(40 CHAR) PRIMARY KEY,
                         UserID          VARCHAR2(40 CHAR) NOT NULL UNIQUE,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

-- 5. Category (renamed from 'categories' for consistency if preferred, sticking to original for now)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE categories CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE categories (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Oracle 12c+ for auto-increment
                            name VARCHAR2(255 CHAR) NOT NULL,
                            parent_id NUMBER DEFAULT NULL,
                            sort_order NUMBER DEFAULT 0,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE CASCADE
);

-- Insert statements for categories are largely the same
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (1, 'Phát triển', NULL, 1);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (33, 'Kinh doanh', NULL, 2);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (41, 'CNTT & Phần mềm', NULL, 3);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (49, 'Thiết kế', NULL, 4);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (56, 'Marketing', NULL, 5);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (63, 'Phát triển cá nhân', NULL, 6);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (69, 'Âm nhạc', NULL, 7);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (73, 'Sức khỏe & Thể hình', NULL, 8);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (78, 'Giảng dạy & Học thuật', NULL, 9);

INSERT INTO categories (id, name, parent_id, sort_order) VALUES (2, 'Lập trình Web', 1, 1);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (14, 'Lập trình Mobile', 1, 2);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (20, 'Lập trình Game', 1, 3);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (24, 'Phát triển phần mềm', 1, 4);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (30, 'Lập trình nhúng / IoT', 1, 5);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (31, 'Blockchain', 1, 6);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (32, 'No-Code Development', 1, 7);

INSERT INTO categories (id, name, parent_id, sort_order) VALUES (3, 'HTML & CSS', 2, 1);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (4, 'JavaScript', 2, 2);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (5, 'ReactJS', 2, 3);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (6, 'VueJS', 2, 4);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (7, 'Angular', 2, 5);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (8, 'PHP', 2, 6);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (9, 'Laravel', 2, 7);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (10, 'ASP.NET', 2, 8);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (11, 'Django', 2, 9);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (12, 'NodeJS', 2, 10);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (13, 'Web APIs', 2, 11);

INSERT INTO categories (id, name, parent_id, sort_order) VALUES (15, 'Android Development', 14, 1);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (16, 'iOS Development', 14, 2);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (17, 'React Native', 14, 3);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (18, 'Flutter', 14, 4);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (19, 'Xamarin', 14, 5);

INSERT INTO categories (id, name, parent_id, sort_order) VALUES (21, 'Unity', 20, 1);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (22, 'Unreal Engine', 20, 2);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (23, 'Godot', 20, 3);

INSERT INTO categories (id, name, parent_id, sort_order) VALUES (25, 'Python', 24, 1);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (26, 'Java', 24, 2);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (27, 'C++', 24, 3);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (28, 'C#', 24, 4);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (29, 'Rust', 24, 5);

INSERT INTO categories (id, name, parent_id, sort_order) VALUES (34, 'Quản trị kinh doanh', 33, 1);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (35, 'Doanh nghiệp khởi nghiệp', 33, 2);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (36, 'Quản lý dự án', 33, 3);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (37, 'Agile & Scrum', 33, 4);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (38, 'Tài chính & Kế toán', 33, 5);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (39, 'Phân tích kinh doanh (Business Analytics)', 33, 6);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (40, 'Nhân sự (HR)', 33, 7);

INSERT INTO categories (id, name, parent_id, sort_order) VALUES (42, 'Mạng máy tính & Bảo mật', 41, 1);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (43, 'Ethical Hacking', 41, 2);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (44, 'Khoa học dữ liệu (Data Science)', 41, 3);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (45, 'Trí tuệ nhân tạo (AI)', 41, 4);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (46, 'Hệ điều hành (Linux, Windows Server)', 41, 5);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (47, 'DevOps', 41, 6);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (48, 'Kiểm thử phần mềm (Software Testing)', 41, 7);

INSERT INTO categories (id, name, parent_id, sort_order) VALUES (50, 'Thiết kế Web', 49, 1);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (51, 'Thiết kế UI/UX', 49, 2);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (52, 'Adobe Photoshop', 49, 3);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (53, 'Illustrator', 49, 4);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (54, 'Thiết kế đồ họa 2D/3D', 49, 5);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (55, 'Thiết kế sản phẩm', 49, 6);

INSERT INTO categories (id, name, parent_id, sort_order) VALUES (57, 'Digital Marketing', 56, 1);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (58, 'SEO', 56, 2);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (59, 'Google Ads / Facebook Ads', 56, 3);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (60, 'Content Marketing', 56, 4);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (61, 'Email Marketing', 56, 5);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (62, 'Affiliate Marketing', 56, 6);

INSERT INTO categories (id, name, parent_id, sort_order) VALUES (64, 'Kỹ năng giao tiếp', 63, 1);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (65, 'Lãnh đạo', 63, 2);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (66, 'Quản lý thời gian', 63, 3);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (67, 'Tư duy phản biện', 63, 4);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (68, 'Đọc nhanh & Ghi nhớ', 63, 5);

INSERT INTO categories (id, name, parent_id, sort_order) VALUES (70, 'Nhạc cụ (Piano, Guitar, v.v.)', 69, 1);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (71, 'Sản xuất âm nhạc', 69, 2);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (72, 'DJ & Âm thanh điện tử', 69, 3);

INSERT INTO categories (id, name, parent_id, sort_order) VALUES (74, 'Yoga', 73, 1);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (75, 'Thiền', 73, 2);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (76, 'Dinh dưỡng', 73, 3);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (77, 'Tập luyện thể hình', 73, 4);

INSERT INTO categories (id, name, parent_id, sort_order) VALUES (79, 'Toán học', 78, 1);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (80, 'Vật lý', 78, 2);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (81, 'Lập trình cho trẻ em', 78, 3);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (82, 'Khoa học máy tính', 78, 4);
INSERT INTO categories (id, name, parent_id, sort_order) VALUES (83, 'IELTS, TOEIC, TOEFL', 78, 5);

-- 6. Course
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Course CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE Course (
                        CourseID    VARCHAR2(40 CHAR) PRIMARY KEY,
                        Title       VARCHAR2(255 CHAR) NOT NULL,
                        Description CLOB,
                        Price       NUMBER(10,2) NOT NULL,
                        CreatedBy   VARCHAR2(40 CHAR) NOT NULL, -- Consider FK to Users(UserID)
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CourseInstructor CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE CourseInstructor (
                                  CourseID      VARCHAR2(40 CHAR),
                                  InstructorID  VARCHAR2(40 CHAR),
                                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                  PRIMARY KEY (CourseID, InstructorID),
                                  FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE,
                                  FOREIGN KEY (InstructorID) REFERENCES Instructor(InstructorID) ON DELETE CASCADE
);

-- 7. CourseCategory
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CourseCategory CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE CourseCategory (
                                CourseID   VARCHAR2(40 CHAR) NOT NULL,
                                CategoryID NUMBER NOT NULL,
                                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                PRIMARY KEY (CourseID, CategoryID),
                                FOREIGN KEY (CourseID)   REFERENCES Course(CourseID),
                                FOREIGN KEY (CategoryID) REFERENCES categories(id)
);

-- 8. Chapter
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CourseChapter CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE CourseChapter (
                               ChapterID    VARCHAR2(40 CHAR) PRIMARY KEY,
                               CourseID     VARCHAR2(40 CHAR) NOT NULL,
                               Title        VARCHAR2(255 CHAR) NOT NULL,
                               Description  CLOB,
                               SortOrder    NUMBER DEFAULT 0 NOT NULL,
                               created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               FOREIGN KEY (CourseID) REFERENCES Course(CourseID)
);

-- 9. Lesson
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CourseLesson CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE CourseLesson (
                              LessonID    VARCHAR2(40 CHAR) PRIMARY KEY,
                              CourseID    VARCHAR2(40 CHAR) NOT NULL,
                              ChapterID   VARCHAR2(40 CHAR) NOT NULL,
                              Title       VARCHAR2(255 CHAR) NOT NULL,
                              Content     CLOB,
                              SortOrder   NUMBER DEFAULT 0 NOT NULL,
                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              FOREIGN KEY (CourseID)  REFERENCES Course(CourseID), -- Changed from CourseChapter(CourseID)
                              FOREIGN KEY (ChapterID) REFERENCES CourseChapter(ChapterID)
);

-- 10. Video
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CourseVideo CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE CourseVideo (
                             VideoID    VARCHAR2(40 CHAR) PRIMARY KEY,
                             LessonID   VARCHAR2(40 CHAR) NOT NULL,
                             Url        VARCHAR2(255 CHAR) NOT NULL, -- Consider up to 4000 CHAR for URLs if needed
                             Title      VARCHAR2(255 CHAR),
                             Duration   NUMBER DEFAULT 0 NOT NULL,
                             SortOrder  NUMBER DEFAULT 0 NOT NULL,
                             created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             FOREIGN KEY (LessonID) REFERENCES CourseLesson(LessonID)
);

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CourseResource CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE CourseResource (
                                ResourceID    VARCHAR2(40 CHAR) PRIMARY KEY,
                                LessonID   VARCHAR2(40 CHAR) NOT NULL,
                                ResourcePath VARCHAR2(255 CHAR) NOT NULL,
                                Title      VARCHAR2(255 CHAR),
                                SortOrder  NUMBER DEFAULT 0 NOT NULL,
                                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                FOREIGN KEY (LessonID) REFERENCES CourseLesson(LessonID)
);

-- 11. CourseImage
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CourseImage CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE CourseImage (
                             ImageID    VARCHAR2(40 CHAR) PRIMARY KEY,
                             CourseID   VARCHAR2(40 CHAR) NOT NULL,
                             ImagePath  VARCHAR2(255 CHAR) NOT NULL,
                             Caption    VARCHAR2(255 CHAR),
                             SortOrder  NUMBER DEFAULT 0 NOT NULL,
                             created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE
);

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CourseObjective CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE CourseObjective (
                                 ObjectiveID VARCHAR2(40 CHAR) PRIMARY KEY, -- Assumed PK
                                 CourseID VARCHAR2(40 CHAR) NOT NULL,
                                 Objective VARCHAR2(255 CHAR) NOT NULL,
                                 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- Added created_at based on pattern
                                 FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE
);

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CourseRequirement CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE CourseRequirement (
                                   RequirementID VARCHAR2(40 CHAR) PRIMARY KEY, -- Assumed PK
                                   CourseID VARCHAR2(40 CHAR) NOT NULL,
                                   Requirement VARCHAR2(255 CHAR) NOT NULL,
                                   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- Added created_at
                                   FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE
);

-- 12. Cart
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Cart CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE Cart (
                      CartID VARCHAR2(40 CHAR) PRIMARY KEY,
                      UserID VARCHAR2(40 CHAR) NOT NULL UNIQUE,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                      FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

-- 13. CartItem
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CartItem CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE CartItem (
                          CartItemID VARCHAR2(40 CHAR) PRIMARY KEY,
                          CartID     VARCHAR2(40 CHAR) NOT NULL,
                          CourseID   VARCHAR2(40 CHAR) NOT NULL,
                          Quantity   NUMBER NOT NULL CHECK (Quantity > 0),
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          FOREIGN KEY (CartID)   REFERENCES Cart(CartID),
                          FOREIGN KEY (CourseID) REFERENCES Course(CourseID)
);

-- 14. Orders
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Orders CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE Orders (
                        OrderID     VARCHAR2(40 CHAR) PRIMARY KEY,
                        UserID      VARCHAR2(40 CHAR) NOT NULL,
                        OrderDate   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- Added NOT NULL
                        TotalAmount NUMBER(10,2) NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

-- 15. OrderDetail
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE OrderDetail CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE OrderDetail (
                             OrderID  VARCHAR2(40 CHAR) NOT NULL,
                             CourseID VARCHAR2(40 CHAR) NOT NULL,
                             Price    NUMBER(10,2) NOT NULL,
                             created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             PRIMARY KEY (OrderID, CourseID),
                             FOREIGN KEY (OrderID)  REFERENCES Orders(OrderID),
                             FOREIGN KEY (CourseID) REFERENCES Course(CourseID)
);

-- 16. Review
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Review CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE Review (
                        ReviewID VARCHAR2(40 CHAR) PRIMARY KEY,
                        UserID   VARCHAR2(40 CHAR) NOT NULL,
                        CourseID VARCHAR2(40 CHAR) NOT NULL,
                        Rating   NUMBER NOT NULL CHECK (Rating BETWEEN 1 AND 5),
                        Comment  CLOB,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        FOREIGN KEY (UserID)   REFERENCES Users(UserID),
                        FOREIGN KEY (CourseID) REFERENCES Course(CourseID)
);

-- 17. Payment
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Payment CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE Payment (
                         PaymentID      VARCHAR2(40 CHAR) PRIMARY KEY,
                         OrderID        VARCHAR2(40 CHAR) NOT NULL,
                         PaymentDate    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- Added NOT NULL
                         PaymentMethod  VARCHAR2(50 CHAR),
                         PaymentStatus  VARCHAR2(50 CHAR),
                         Amount         NUMBER(10,2) NOT NULL,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
);

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE password_resets CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
CREATE TABLE password_resets (
                                 id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 email VARCHAR2(100 CHAR) NOT NULL,
                                 token VARCHAR2(255 CHAR) NOT NULL,
                                 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL -- Original ALTER is not needed if defined correctly here
);

-- Create index separately in Oracle
CREATE INDEX idx_password_resets_email ON password_resets(email);

-- The ALTER TABLE for password_resets.created_at is redundant if the
-- CREATE TABLE statement already defines it as TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP.
-- If it were different, the syntax would be:
-- ALTER TABLE password_resets MODIFY (created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

COMMIT;