-- Script SQL được cập nhật để sử dụng UTC+7 cho các cột TIMESTAMP

CREATE TABLE Role (
                      RoleID      VARCHAR2(20 CHAR) CONSTRAINT pk_role PRIMARY KEY,
                      RoleName    VARCHAR2(50 CHAR) CONSTRAINT uq_role_rolename UNIQUE NOT NULL,
                      created_at TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL
);

MERGE INTO Role tgt
USING (SELECT 'student' AS RoleID, 'Học sinh' AS RoleName FROM dual) src
ON (tgt.RoleID = src.RoleID)
WHEN MATCHED THEN
    UPDATE SET tgt.RoleName = src.RoleName
WHEN NOT MATCHED THEN
    INSERT (RoleID, RoleName, created_at) VALUES (src.RoleID, src.RoleName, CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP));

MERGE INTO Role tgt
USING (SELECT 'instructor' AS RoleID, 'Giảng viên' AS RoleName FROM dual) src
ON (tgt.RoleID = src.RoleID)
WHEN MATCHED THEN
    UPDATE SET tgt.RoleName = src.RoleName
WHEN NOT MATCHED THEN
    INSERT (RoleID, RoleName, created_at) VALUES (src.RoleID, src.RoleName, CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP));

MERGE INTO Role tgt
USING (SELECT 'admin' AS RoleID, 'Quản trị viên' AS RoleName FROM dual) src
ON (tgt.RoleID = src.RoleID)
WHEN MATCHED THEN
    UPDATE SET tgt.RoleName = src.RoleName
WHEN NOT MATCHED THEN
    INSERT (RoleID, RoleName, created_at) VALUES (src.RoleID, src.RoleName, CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP));

CREATE TABLE Users (
                       UserID       VARCHAR2(40 CHAR) CONSTRAINT pk_users PRIMARY KEY,
                       FirstName    VARCHAR2(100 CHAR) NOT NULL,
                       LastName     VARCHAR2(100 CHAR) NOT NULL,
                       Email        VARCHAR2(100 CHAR) CONSTRAINT uq_users_email UNIQUE NOT NULL,
                       Password     VARCHAR2(255 CHAR) NOT NULL,
                       RoleID       VARCHAR2(20 CHAR) NOT NULL,
                       ProfileImage VARCHAR2(255 CHAR),
                       created_at   TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                       CONSTRAINT fk_users_role FOREIGN KEY (RoleID) REFERENCES Role(RoleID)
);

CREATE TABLE Instructor (
                            InstructorID VARCHAR2(40 CHAR) CONSTRAINT pk_instructor PRIMARY KEY,
                            UserID       VARCHAR2(40 CHAR) CONSTRAINT uq_instructor_userid UNIQUE NOT NULL,
                            Biography    CLOB,
                            created_at   TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                            CONSTRAINT fk_instructor_users FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE Student (
                         StudentID  VARCHAR2(40 CHAR) CONSTRAINT pk_student PRIMARY KEY,
                         UserID     VARCHAR2(40 CHAR) CONSTRAINT uq_student_userid UNIQUE NOT NULL,
                         created_at TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                         CONSTRAINT fk_student_users FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE categories (
                            id          NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_categories PRIMARY KEY,
                            name        VARCHAR2(255 CHAR) NOT NULL,
                            parent_id   NUMBER DEFAULT NULL,
                            sort_order  NUMBER DEFAULT 0,
                            created_at  TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                            CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);




CREATE TABLE Course (
                        CourseID    VARCHAR2(40 CHAR) CONSTRAINT pk_course PRIMARY KEY,
                        Title       VARCHAR2(255 CHAR) NOT NULL,
                        Description CLOB,
                        Price       NUMBER(10,2) NOT NULL,
                        Difficulty  VARCHAR2(40 CHAR),
                        Language    VARCHAR2(40 CHAR),
                        CreatedBy   VARCHAR2(40 CHAR) NOT NULL,
                        created_at  TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL
);

CREATE TABLE CourseInstructor (
                                  CourseID     VARCHAR2(40 CHAR),
                                  InstructorID VARCHAR2(40 CHAR),
                                  created_at   TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                  CONSTRAINT pk_courseinstructor PRIMARY KEY (CourseID, InstructorID),
                                  CONSTRAINT fk_ci_course FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE,
                                  CONSTRAINT fk_ci_instructor FOREIGN KEY (InstructorID) REFERENCES Instructor(InstructorID) ON DELETE CASCADE
);

CREATE TABLE CourseCategory (
                                CourseID   VARCHAR2(40 CHAR) NOT NULL,
                                CategoryID NUMBER NOT NULL,
                                created_at TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                CONSTRAINT pk_coursecategory PRIMARY KEY (CourseID, CategoryID),
                                CONSTRAINT fk_cc_course FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE,
                                CONSTRAINT fk_cc_category FOREIGN KEY (CategoryID) REFERENCES categories(id) ON DELETE CASCADE
);

CREATE TABLE CourseChapter (
                               ChapterID   VARCHAR2(40 CHAR) CONSTRAINT pk_coursechapter PRIMARY KEY,
                               CourseID    VARCHAR2(40 CHAR) NOT NULL,
                               Title       VARCHAR2(255 CHAR) NOT NULL,
                               Description CLOB,
                               SortOrder   NUMBER DEFAULT 0 NOT NULL,
                               created_at  TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                               CONSTRAINT fk_chapter_course FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE
);

CREATE TABLE CourseLesson (
                              LessonID    VARCHAR2(40 CHAR) CONSTRAINT pk_courselesson PRIMARY KEY,
                              CourseID    VARCHAR2(40 CHAR) NOT NULL,
                              ChapterID   VARCHAR2(40 CHAR) NOT NULL,
                              Title       VARCHAR2(255 CHAR) NOT NULL,
                              Content     CLOB,
                              SortOrder   NUMBER DEFAULT 0 NOT NULL,
                              created_at  TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                              CONSTRAINT fk_lesson_course FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE,
                              CONSTRAINT fk_lesson_chapter FOREIGN KEY (ChapterID) REFERENCES CourseChapter(ChapterID) ON DELETE CASCADE
);

CREATE TABLE CourseVideo (
                             VideoID    VARCHAR2(40 CHAR) CONSTRAINT pk_coursevideo PRIMARY KEY,
                             LessonID   VARCHAR2(40 CHAR) NOT NULL,
                             Url        VARCHAR2(255 CHAR) NOT NULL,
                             Title      VARCHAR2(255 CHAR),
                             Duration   NUMBER DEFAULT 0 NOT NULL,
                             SortOrder  NUMBER DEFAULT 0 NOT NULL,
                             created_at TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                             CONSTRAINT fk_video_lesson FOREIGN KEY (LessonID) REFERENCES CourseLesson(LessonID) ON DELETE CASCADE
);

CREATE TABLE CourseResource (
                                ResourceID   VARCHAR2(40 CHAR) CONSTRAINT pk_courseresource PRIMARY KEY,
                                LessonID     VARCHAR2(40 CHAR) NOT NULL,
                                ResourcePath VARCHAR2(255 CHAR) NOT NULL,
                                Title        VARCHAR2(255 CHAR),
                                SortOrder    NUMBER DEFAULT 0 NOT NULL,
                                created_at   TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                CONSTRAINT fk_resource_lesson FOREIGN KEY (LessonID) REFERENCES CourseLesson(LessonID) ON DELETE CASCADE
);

CREATE TABLE CourseImage (
                             ImageID    VARCHAR2(40 CHAR) CONSTRAINT pk_courseimage PRIMARY KEY,
                             CourseID   VARCHAR2(40 CHAR) NOT NULL,
                             ImagePath  VARCHAR2(255 CHAR) NOT NULL,
                             Caption    VARCHAR2(255 CHAR),
                             SortOrder  NUMBER DEFAULT 0 NOT NULL,
                             created_at TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                             CONSTRAINT fk_image_course FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE
);

CREATE TABLE CourseObjective (
                                 ObjectiveID VARCHAR2(40 CHAR) NOT NULL,
                                 CourseID    VARCHAR2(40 CHAR) NOT NULL,
                                 Objective   VARCHAR2(255 CHAR) NOT NULL,
                                 created_at  TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                 CONSTRAINT pk_courseobjective PRIMARY KEY (CourseID, ObjectiveID),
                                 CONSTRAINT fk_objective_course FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE
);

CREATE TABLE CourseRequirement (
                                   RequirementID VARCHAR2(40 CHAR) NOT NULL,
                                   CourseID      VARCHAR2(40 CHAR) NOT NULL,
                                   Requirement   VARCHAR2(255 CHAR) NOT NULL,
                                   created_at    TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                   CONSTRAINT pk_courserequirement PRIMARY KEY (CourseID, RequirementID),
                                   CONSTRAINT fk_requirement_course FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE
);

CREATE TABLE Cart (
                      CartID     VARCHAR2(40 CHAR) CONSTRAINT pk_cart PRIMARY KEY,
                      UserID     VARCHAR2(40 CHAR) CONSTRAINT uq_cart_userid UNIQUE NOT NULL,
                      created_at TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                      CONSTRAINT fk_cart_users FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE CartItem (
                          CartItemID VARCHAR2(40 CHAR) CONSTRAINT pk_cartitem PRIMARY KEY,
                          CartID     VARCHAR2(40 CHAR) NOT NULL,
                          CourseID   VARCHAR2(40 CHAR) NOT NULL,
                          Quantity   NUMBER NOT NULL,
                          created_at TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                          CONSTRAINT fk_cartitem_cart FOREIGN KEY (CartID) REFERENCES Cart(CartID) ON DELETE CASCADE,
                          CONSTRAINT fk_cartitem_course FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE,
                          CONSTRAINT ck_cartitem_quantity CHECK (Quantity > 0)
);

CREATE TABLE Orders (
                        OrderID     VARCHAR2(40 CHAR) CONSTRAINT pk_orders PRIMARY KEY,
                        UserID      VARCHAR2(40 CHAR) NOT NULL,
                        OrderDate   TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP),
                        TotalAmount NUMBER(10,2) NOT NULL,
                        created_at  TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                        CONSTRAINT fk_orders_users FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE SET NULL
);

CREATE TABLE OrderDetail (
                             OrderID  VARCHAR2(40 CHAR) NOT NULL,
                             CourseID VARCHAR2(40 CHAR) NOT NULL,
                             Price    NUMBER(10,2) NOT NULL,
                             created_at TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                             CONSTRAINT pk_orderdetail PRIMARY KEY (OrderID, CourseID),
                             CONSTRAINT fk_detail_orders FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE,
                             CONSTRAINT fk_detail_course FOREIGN KEY (CourseID) REFERENCES Course(CourseID)
);

CREATE TABLE Review (
                        ReviewID   VARCHAR2(40 CHAR) CONSTRAINT pk_review PRIMARY KEY,
                        UserID     VARCHAR2(40 CHAR) NOT NULL,
                        CourseID   VARCHAR2(40 CHAR) NOT NULL,
                        Rating     NUMBER NOT NULL,
                        ReviewText CLOB,
                        created_at TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                        CONSTRAINT fk_review_users FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
                        CONSTRAINT fk_review_course FOREIGN KEY (CourseID) REFERENCES Course(CourseID) ON DELETE CASCADE,
                        CONSTRAINT ck_review_rating CHECK (Rating BETWEEN 1 AND 5)
);

CREATE TABLE Payment (
                         PaymentID     VARCHAR2(40 CHAR) CONSTRAINT pk_payment PRIMARY KEY,
                         OrderID       VARCHAR2(40 CHAR) NOT NULL,
                         PaymentDate   TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP),
                         PaymentMethod VARCHAR2(50 CHAR),
                         PaymentStatus VARCHAR2(50 CHAR),
                         Amount        NUMBER(10,2) NOT NULL,
                         created_at    TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                         CONSTRAINT fk_payment_orders FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
);

CREATE TABLE password_resets (
                                 id         NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_password_resets PRIMARY KEY,
                                 email      VARCHAR2(100 CHAR) NOT NULL,
                                 token      VARCHAR2(255 CHAR) NOT NULL,
                                 created_at TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL
);

CREATE INDEX idx_password_resets_email ON password_resets(email);

-- History Tables
-- Lưu ý: created_at_original sẽ lưu giá trị đã được chuyển đổi sang UTC+7 từ bảng gốc
-- DML_Timestamp cũng sẽ được lưu trữ theo UTC+7

CREATE TABLE Users_History (
                               HistoryID         NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_users_history PRIMARY KEY,
                               UserID            VARCHAR2(40 CHAR),
                               FirstName         VARCHAR2(100 CHAR),
                               LastName          VARCHAR2(100 CHAR),
                               Email             VARCHAR2(100 CHAR),
                               Password          VARCHAR2(255 CHAR),
                               RoleID            VARCHAR2(20 CHAR),
                               ProfileImage      VARCHAR2(255 CHAR),
                               created_at_original TIMESTAMP,
                               DML_Type          VARCHAR2(10 CHAR) NOT NULL,
                               DML_Timestamp     TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                               DML_User          VARCHAR2(128 CHAR)
);

CREATE TABLE Course_History (
                                HistoryID         NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_course_history PRIMARY KEY,
                                CourseID          VARCHAR2(40 CHAR),
                                Title             VARCHAR2(255 CHAR),
                                Description       CLOB,
                                Price             NUMBER(10,2),
                                Difficulty        VARCHAR2(40 CHAR),
                                Language          VARCHAR2(40 CHAR),
                                CreatedBy         VARCHAR2(40 CHAR),
                                created_at_original TIMESTAMP,
                                DML_Type          VARCHAR2(10 CHAR) NOT NULL,
                                DML_Timestamp     TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                DML_User          VARCHAR2(128 CHAR)
);

CREATE TABLE Orders_History (
                                HistoryID         NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_orders_history PRIMARY KEY,
                                OrderID           VARCHAR2(40 CHAR),
                                UserID            VARCHAR2(40 CHAR),
                                OrderDate         TIMESTAMP, -- Lưu ý: OrderDate gốc cũng đã được chuyển đổi
                                TotalAmount       NUMBER(10,2),
                                created_at_original TIMESTAMP,
                                DML_Type          VARCHAR2(10 CHAR) NOT NULL,
                                DML_Timestamp     TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                DML_User          VARCHAR2(128 CHAR)
);

CREATE TABLE Role_History (
                              HistoryID         NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_role_history PRIMARY KEY,
                              RoleID            VARCHAR2(20 CHAR),
                              RoleName          VARCHAR2(50 CHAR),
                              created_at_original TIMESTAMP,
                              DML_Type          VARCHAR2(10 CHAR) NOT NULL,
                              DML_Timestamp     TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                              DML_User          VARCHAR2(128 CHAR)
);

CREATE TABLE Instructor_History (
                                    HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_instructor_history PRIMARY KEY,
                                    InstructorID        VARCHAR2(40 CHAR),
                                    UserID              VARCHAR2(40 CHAR),
                                    Biography           CLOB,
                                    created_at_original TIMESTAMP,
                                    DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                    DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                    DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE Student_History (
                                 HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_student_history PRIMARY KEY,
                                 StudentID           VARCHAR2(40 CHAR),
                                 UserID              VARCHAR2(40 CHAR),
                                 created_at_original TIMESTAMP,
                                 DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                 DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                 DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE categories_History (
                                    HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_categories_history PRIMARY KEY,
                                    id                  NUMBER,
                                    name                VARCHAR2(255 CHAR),
                                    parent_id           NUMBER,
                                    sort_order          NUMBER,
                                    created_at_original TIMESTAMP,
                                    DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                    DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                    DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE CourseInstructor_History (
                                          HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_courseinstructor_hist PRIMARY KEY,
                                          CourseID            VARCHAR2(40 CHAR),
                                          InstructorID        VARCHAR2(40 CHAR),
                                          created_at_original TIMESTAMP,
                                          DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                          DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                          DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE CourseCategory_History (
                                        HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_coursecategory_hist PRIMARY KEY,
                                        CourseID            VARCHAR2(40 CHAR),
                                        CategoryID          NUMBER,
                                        created_at_original TIMESTAMP,
                                        DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                        DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                        DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE CourseChapter_History (
                                       HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_coursechapter_hist PRIMARY KEY,
                                       ChapterID           VARCHAR2(40 CHAR),
                                       CourseID            VARCHAR2(40 CHAR),
                                       Title               VARCHAR2(255 CHAR),
                                       Description         CLOB,
                                       SortOrder           NUMBER,
                                       created_at_original TIMESTAMP,
                                       DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                       DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                       DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE CourseLesson_History (
                                      HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_courselesson_hist PRIMARY KEY,
                                      LessonID            VARCHAR2(40 CHAR),
                                      CourseID            VARCHAR2(40 CHAR),
                                      ChapterID           VARCHAR2(40 CHAR),
                                      Title               VARCHAR2(255 CHAR),
                                      Content             CLOB,
                                      SortOrder           NUMBER,
                                      created_at_original TIMESTAMP,
                                      DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                      DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                      DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE CourseVideo_History (
                                     HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_coursevideo_hist PRIMARY KEY,
                                     VideoID             VARCHAR2(40 CHAR),
                                     LessonID            VARCHAR2(40 CHAR),
                                     Url                 VARCHAR2(255 CHAR),
                                     Title               VARCHAR2(255 CHAR),
                                     Duration            NUMBER,
                                     SortOrder           NUMBER,
                                     created_at_original TIMESTAMP,
                                     DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                     DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                     DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE CourseResource_History (
                                        HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_courseresource_hist PRIMARY KEY,
                                        ResourceID          VARCHAR2(40 CHAR),
                                        LessonID            VARCHAR2(40 CHAR),
                                        ResourcePath        VARCHAR2(255 CHAR),
                                        Title               VARCHAR2(255 CHAR),
                                        SortOrder           NUMBER,
                                        created_at_original TIMESTAMP,
                                        DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                        DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                        DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE CourseImage_History (
                                     HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_courseimage_hist PRIMARY KEY,
                                     ImageID             VARCHAR2(40 CHAR),
                                     CourseID            VARCHAR2(40 CHAR),
                                     ImagePath           VARCHAR2(255 CHAR),
                                     Caption             VARCHAR2(255 CHAR),
                                     SortOrder           NUMBER,
                                     created_at_original TIMESTAMP,
                                     DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                     DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                     DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE CourseObjective_History (
                                         HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_courseobjective_hist PRIMARY KEY,
                                         ObjectiveID         VARCHAR2(40 CHAR),
                                         CourseID            VARCHAR2(40 CHAR),
                                         Objective           VARCHAR2(255 CHAR),
                                         created_at_original TIMESTAMP,
                                         DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                         DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                         DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE CourseRequirement_History (
                                           HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_courserequirement_hist PRIMARY KEY,
                                           RequirementID       VARCHAR2(40 CHAR),
                                           CourseID            VARCHAR2(40 CHAR),
                                           Requirement         VARCHAR2(255 CHAR),
                                           created_at_original TIMESTAMP,
                                           DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                           DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                           DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE Cart_History (
                              HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_cart_history PRIMARY KEY,
                              CartID              VARCHAR2(40 CHAR),
                              UserID              VARCHAR2(40 CHAR),
                              created_at_original TIMESTAMP,
                              DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                              DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                              DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE CartItem_History (
                                  HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_cartitem_history PRIMARY KEY,
                                  CartItemID          VARCHAR2(40 CHAR),
                                  CartID              VARCHAR2(40 CHAR),
                                  CourseID            VARCHAR2(40 CHAR),
                                  Quantity            NUMBER,
                                  created_at_original TIMESTAMP,
                                  DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                  DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                  DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE OrderDetail_History (
                                     HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_orderdetail_hist PRIMARY KEY,
                                     OrderID             VARCHAR2(40 CHAR),
                                     CourseID            VARCHAR2(40 CHAR),
                                     Price               NUMBER(10,2),
                                     created_at_original TIMESTAMP,
                                     DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                     DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                     DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE Review_History (
                                HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_review_history PRIMARY KEY,
                                ReviewID            VARCHAR2(40 CHAR),
                                UserID              VARCHAR2(40 CHAR),
                                CourseID            VARCHAR2(40 CHAR),
                                Rating              NUMBER,
                                ReviewText          CLOB,
                                created_at_original TIMESTAMP,
                                DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE Payment_History (
                                 HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_payment_history PRIMARY KEY,
                                 PaymentID           VARCHAR2(40 CHAR),
                                 OrderID             VARCHAR2(40 CHAR),
                                 PaymentDate         TIMESTAMP, -- Lưu ý: PaymentDate gốc cũng đã được chuyển đổi
                                 PaymentMethod       VARCHAR2(50 CHAR),
                                 PaymentStatus       VARCHAR2(50 CHAR),
                                 Amount              NUMBER(10,2),
                                 created_at_original TIMESTAMP,
                                 DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                 DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                 DML_User            VARCHAR2(128 CHAR)
);

CREATE TABLE password_resets_History (
                                         HistoryID           NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_password_resets_hist PRIMARY KEY,
                                         id                  NUMBER,
                                         email               VARCHAR2(100 CHAR),
                                         token               VARCHAR2(255 CHAR),
                                         created_at_original TIMESTAMP,
                                         DML_Type            VARCHAR2(10 CHAR) NOT NULL,
                                         DML_Timestamp       TIMESTAMP DEFAULT CAST(SYSTIMESTAMP AT TIME ZONE 'Asia/Ho_Chi_Minh' AS TIMESTAMP) NOT NULL,
                                         DML_User            VARCHAR2(128 CHAR)
);

COMMIT;
