name: PHP CI

on:
  push:
    branches: ["feature/mysql"]
  pull_request:
    branches: ["feature/mysql"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout source code
        uses: actions/checkout@v4

      - name: 🧾 Validate composer.json and composer.lock
        run: composer validate --strict

      - name: 📦 Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: 📥 Install dependencies
        run: composer install --prefer-dist --no-progress

      # ====== PHPStan Check Standard ======
      - name: 🔍 PHPStan - Check DTO
        run: vendor/bin/phpstan analyse model/dto --memory-limit=1G

      - name: 🔍 PHPStan - Check Service
        run: vendor/bin/phpstan analyse model/dto --memory-limit=1G

      - name: 🔍 PHPStan - Check Controllers
        run: vendor/bin/phpstan analyse controller --memory-limit=1G

      - name: 🔍 PHPStan - Check BLL
        run: vendor/bin/phpstan analyse tests model/bll --memory-limit=1G

      - name: 🔍 PHPStan - Check API
        run: vendor/bin/phpstan analyse api --memory-limit=1G

      - name: 🔍 PHPStan - Check Tests
        run: vendor/bin/phpstan analyse tests --memory-limit=1G

      - name: 🛠 Set execute permission for bash script
        run: chmod +x ci_cd/init_essential.bash

      - name: 🚀 Run Init Database Sequence via bash script
        run: ./ci_cd/init_essential.bash github yes

      # ====== PHPUnit Test ======
      - name: 🧪 Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml --colors=always

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: 🚀 Deploy to EC2
        if: success()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 1800
          script: |
            cd ~/
            git clone -b "feature/mysql" "https://github.com/thavananh/CoursePro1.git"
            sudo cp CoursePro1/ci_cd/* ~/
            sudo rm -rf CoursePro1
            sudo ./init_essential.bash normal yes 50
